import { defineConfig } from "oxlint";

export default defineConfig({
  ignorePatterns: [
    "apps/web/src/routeTree.gen.ts",
    // Generated by `pnpm client:generate` from the OpenAPI document; never hand-edited, and its
    // `headers: { [name: string]: unknown }` blocks are openapi-typescript's own output shape.
    "packages/contracts/src/generated.ts",
    // Vendored shadcn output, replaced wholesale by the shadcn CLI — hand-edits would be lost.
    "apps/web/src/components/ui/**",
    "tools/oxlint/anti-slop/**",
    ".agents/**",
    ".claude/**",
  ],
  plugins: ["typescript", "unicorn", "oxc", "import", "vitest", "promise", "node", "react"],
  jsPlugins: [{ name: "anti-slop", specifier: "./tools/oxlint/anti-slop/index.ts" }],
  categories: {
    correctness: "error",
    suspicious: "error",
    perf: "warn",
  },
  rules: {
    "unicorn/filename-case": "off",
    "react/react-in-jsx-scope": "off",
    "react/jsx-key": "error",
    // Sequential awaits inside SQL transactions and the v1 import scripts are deliberate: row
    // order and foreign keys depend on the previous statement having committed.
    "no-await-in-loop": "off",
    // `.map((x) => ({ ...x, y }))` is the immutable idiom this codebase prefers; the in-place
    // mutation the rule suggests is a micro-optimisation that would hide aliasing bugs.
    "oxc/no-map-spread": "off",

    "anti-slop/no-chained-type-assertions": "error",
    "anti-slop/no-conditional-empty-object-spread": "error",
    "anti-slop/no-known-value-widening": "error",
    "anti-slop/no-module-mocking": "error",
    "anti-slop/no-object-parameters": "error",
    "anti-slop/no-reflect-apply": "error",
    "anti-slop/no-reflect-get": "error",
    "anti-slop/no-runtime-typeof": ["error", { allowInTypeGuards: true }],
    "anti-slop/no-shape-in-symbol-names": "error",
    "anti-slop/no-unknown-parameters": "error",
    "anti-slop/no-unknown-returns": "error",
    "anti-slop/no-unknown-type-aliases": "error",
    "anti-slop/no-unsafe-dictionary-type": "error",
    "anti-slop/no-widen-then-assert": "error",
    "anti-slop/require-safety-comment-for-type-assertion": "error",
  },
  overrides: [
    {
      // Phase E legacy allowlist (docs/v0.3.5.md §1.0). These are the oversized files Phase E
      // splits or deletes; their untyped-row idiom (`Record<string, unknown>` SQL rows, v1 shape
      // adapters, draft-sync effects) is what the split rewrites, so the anti-slop rules are
      // relaxed here instead of being satisfied twice. The list may only shrink: remove a file
      // the moment its replacement lands, and never add one.
      files: [
        "apps/web/src/features/platform/work-detail-page.tsx",
        "apps/web/src/features/admin/components/editor-form/index.tsx",
        "apps/api/src/app.ts",
        "apps/web/src/features/admin/pages/awards-management-page.tsx",
        "apps/web/src/features/library/player-controls.tsx",
        "apps/web/src/features/admin/json-editor/engine.ts",
        "apps/web/src/features/admin/json-editor/json-editor-page.tsx",
        "packages/contracts/src/index.ts",
        "apps/web/src/features/admin/pages/entities-management-page.tsx",
        "apps/web/src/features/admin/pages/statistics-page.tsx",
        "apps/web/src/features/library/player-page.tsx",
        "apps/web/src/features/social/title-social-section.tsx",
        "apps/api/src/features/social/routes.ts",
        "apps/web/src/features/platform/studio-lineage-page.tsx",
        "apps/web/src/features/admin/pages/profiles-page.tsx",
        "apps/web/src/server/compat.ts",
        "apps/web/src/features/library/compare-page.tsx",
        "apps/web/src/features/platform/database-page.tsx",
        "apps/api/src/repository.ts",
        "apps/web/src/features/library/model.ts",
        "apps/web/src/features/profiles/settings-page.tsx",
        "apps/web/src/features/admin/pages/media-library-page.tsx",
        "apps/api/src/features/archive/routes.ts",
        "apps/web/src/features/catalog/catalog-filters.tsx",
        "apps/api/src/features/accounts/routes.ts",
        "apps/web/src/features/library/offline-title-page.tsx",
        "apps/api/src/integrations/torrent-source.ts",
        "apps/web/src/features/profiles/profiles-page.tsx",
        "apps/web/src/features/admin/pages/planets-management-page.tsx",
        "apps/web/src/server/library.functions.ts",
        "packages/database/src/import-v1-knowledge.ts",
        "packages/database/src/import-v1.ts",
        "packages/database/src/consolidate-v1-franchises.ts",
      ],
      rules: {
        "anti-slop/no-known-value-widening": "off",
        "anti-slop/no-runtime-typeof": "off",
        "anti-slop/no-unknown-parameters": "off",
        "anti-slop/no-unknown-returns": "off",
        "anti-slop/no-unsafe-dictionary-type": "off",
        "anti-slop/no-conditional-empty-object-spread": "off",
        "anti-slop/no-chained-type-assertions": "off",
        "anti-slop/no-shape-in-symbol-names": "off",
        "anti-slop/require-safety-comment-for-type-assertion": "off",
        "react/set-state-in-effect": "off",
      },
    },
  ],
});
