import { z } from "zod";

export const taxonomy = {
  genres: [
    ["action", "Action", "أكشن"],
    ["adventure", "Adventure", "مغامرة"],
    ["comedy", "Comedy", "كوميديا"],
    ["crime", "Crime", "جريمة"],
    ["drama", "Drama", "دراما"],
    ["fantasy", "Fantasy", "فانتازيا"],
    ["historical", "Historical", "تاريخي"],
    ["horror", "Horror", "رعب"],
    ["mecha", "Mecha", "ميكا"],
    ["music", "Music", "موسيقى"],
    ["mystery", "Mystery", "غموض"],
    ["psychological", "Psychological", "نفسي"],
    ["romance", "Romance", "رومانسي"],
    ["science-fiction", "Science Fiction", "خيال علمي"],
    ["slice-of-life", "Slice of Life", "شريحة من الحياة"],
    ["sports", "Sports", "رياضة"],
    ["supernatural", "Supernatural", "خارق للطبيعة"],
    ["thriller", "Thriller", "إثارة"],
    ["war", "War", "حرب"],
  ],
  tones: [
    ["wholesome", "Wholesome", "دافئ"],
    ["emotional", "Emotional", "عاطفي"],
    ["bittersweet", "Bittersweet", "حلو ومر"],
    ["reflective", "Reflective", "تأملي"],
    ["tense", "Tense", "متوتر"],
    ["energetic", "Energetic", "حيوي"],
    ["dark", "Dark", "قاتم"],
    ["whimsical", "Whimsical", "خيالي مرح"],
    ["epic", "Epic", "ملحمي"],
    ["atmospheric", "Atmospheric", "غني بالأجواء"],
  ],
  tags: [
    ["coming-of-age", "Coming of age", "بلوغ ونضج"],
    ["found-family", "Found family", "عائلة مختارة"],
    ["friendship", "Friendship", "صداقة"],
    ["family", "Family", "عائلة"],
    ["magic", "Magic", "سحر"],
    ["school", "School", "مدرسة"],
    ["travel", "Travel", "سفر"],
    ["political", "Political", "سياسي"],
    ["artificial-intelligence", "Artificial intelligence", "ذكاء اصطناعي"],
    ["martial-arts", "Martial arts", "فنون قتالية"],
    ["military", "Military", "عسكري"],
    ["cooking", "Cooking", "طبخ"],
    ["monsters", "Monsters", "وحوش"],
    ["curses", "Curses", "لعنات"],
    ["special-abilities", "Special abilities", "قدرات خاصة"],
    ["training", "Training", "تدريب"],
    ["slow-burn", "Slow burn", "تطور بطيء"],
    ["childhood-classic", "Childhood classic", "كلاسيكية طفولة"],
    ["male-protagonist", "Male Protagonist", "بطل ذكر"],
    ["female-protagonist", "Female Protagonist", "بطلة"],
    ["animated-movie", "Animated Movie", "فيلم رسوم متحركة"],
    ["child-cast", "Child Cast", "شخصيات طفولية"],
    ["ensemble-cast", "Ensemble Cast", "بطولة جماعية"],
    ["teen-cast", "Teen Cast", "شخصيات مراهقة"],
    ["nonhuman-characters", "Nonhuman Characters", "شخصيات غير بشرية"],
    ["animal-cast", "Animal Cast", "شخصيات حيوانية"],
    ["adult-cast", "Adult Cast", "شخصيات بالغة"],
    ["survival", "Survival", "البقاء"],
    ["anime-movie", "Anime Movie", "فيلم أنمي"],
    ["workplace", "Workplace", "مكان العمل"],
    ["urban-setting", "Urban Setting", "بيئة حضرية"],
    ["conspiracy", "Conspiracy", "المؤامرة"],
    ["crime-organization", "Crime Organization", "منظمة إجرامية"],
    ["rural-setting", "Rural Setting", "بيئة ريفية"],
    ["detailed-worldbuilding", "Detailed Worldbuilding", "بناء عالم مفصّل"],
    ["bullying", "Bullying", "التنمّر"],
    ["literary-classic", "Literary Classic", "كلاسيكيات أدبية"],
    ["memory", "Memory", "الذاكرة"],
    ["political-intrigue", "Political Intrigue", "مكائد سياسية"],
    ["revenge", "Revenge", "الانتقام"],
    ["philosophy", "Philosophy", "الفلسفة"],
    ["redemption", "Redemption", "الخلاص"],
    ["sibling-relationship", "Sibling Relationship", "علاقة الأشقاء"],
    ["swordplay", "Swordplay", "المبارزة بالسيوف"],
    ["animals", "Animals", "الحيوانات"],
    ["class-conflict", "Class Conflict", "الصراع الطبقي"],
    ["mental-health", "Mental Health", "الصحة النفسية"],
    ["spirits", "Spirits", "الأرواح"],
    ["demons", "Demons", "الشياطين"],
    ["hidden-identity", "Hidden Identity", "هوية مخفية"],
    ["identity", "Identity", "الهوية"],
    ["mortality", "Mortality", "الفناء"],
    ["robots", "Robots", "الروبوتات"],
    ["antihero", "Antihero", "بطل مضاد"],
    ["grief", "Grief", "الفقد"],
    ["healing", "Healing", "التعافي"],
    ["moral-ambiguity", "Moral Ambiguity", "غموض أخلاقي"],
    ["mythology", "Mythology", "الأساطير"],
    ["parenthood", "Parenthood", "الأبوّة والأمومة"],
    ["time-travel", "Time Travel", "السفر عبر الزمن"],
    ["trauma", "Trauma", "الصدمة النفسية"],
    ["adoption", "Adoption", "التبنّي"],
    ["body-horror", "Body Horror", "رعب جسدي"],
    ["folklore", "Folklore", "الموروث الشعبي"],
    ["prejudice", "Prejudice", "التحيّز"],
    ["rivalry", "Rivalry", "التنافس"],
    ["school-club", "School Club", "نادٍ مدرسي"],
    ["education", "Education", "التعليم"],
    ["episodic", "Episodic", "حلقات مستقلة"],
    ["family-life", "Family Life", "الحياة العائلية"],
    ["mind-games", "Mind Games", "ألعاب ذهنية"],
    ["royal-court", "Royal Court", "البلاط الملكي"],
    ["technology", "Technology", "التقنية"],
    ["art", "Art", "الفن"],
    ["investigation", "Investigation", "التحقيق"],
    ["island-setting", "Island Setting", "بيئة جزيرية"],
    ["manipulation", "Manipulation", "التلاعب"],
    ["maritime-setting", "Maritime Setting", "بيئة بحرية"],
    ["peace-and-nonviolence", "Peace and Nonviolence", "السلام واللاعنف"],
    ["underdog", "Underdog", "شخصية مستضعفة"],
    ["corporate-power", "Corporate Power", "نفوذ الشركات"],
    ["disability", "Disability", "الإعاقة"],
    ["fairy-tales", "Fairy Tales", "حكايات خرافية"],
    ["post-apocalyptic", "Post-Apocalyptic", "ما بعد الكارثة"],
    ["religion", "Religion", "الدين"],
    ["steampunk", "Steampunk", "ستيمبانك"],
    ["toys", "Toys", "الألعاب"],
    ["video-games", "Video Games", "ألعاب الفيديو"],
    ["anthology", "Anthology", "قصص مختارة"],
    ["assassins", "Assassins", "القتلة المأجورون"],
    ["detective", "Detective", "التحقيق البوليسي"],
    ["dystopia", "Dystopia", "ديستوبيا"],
    ["guns", "Guns", "الأسلحة النارية"],
    ["kaiju", "Kaiju", "وحوش عملاقة"],
    ["natural-disaster", "Natural Disaster", "كارثة طبيعية"],
    ["police", "Police", "الشرطة"],
    ["prehistoric-life", "Prehistoric Life", "حياة ما قبل التاريخ"],
    ["racing", "Racing", "السباقات"],
    ["rebellion", "Rebellion", "التمرد"],
    ["social-anxiety", "Social Anxiety", "القلق الاجتماعي"],
    ["witches", "Witches", "الساحرات"],
    ["aliens", "Aliens", "كائنات فضائية"],
    ["childhood", "Childhood", "الطفولة"],
    ["college", "College", "الجامعة"],
    ["dragons", "Dragons", "التنانين"],
    ["environment", "Environment", "البيئة"],
    ["espionage", "Espionage", "التجسس"],
    ["fugitive", "Fugitive", "مطارد"],
    ["gods", "Gods", "الآلهة"],
    ["idol-industry", "Idol Industry", "صناعة الآيدول"],
    ["intergenerational-conflict", "Intergenerational Conflict", "صراع الأجيال"],
    ["lost-civilization", "Lost Civilization", "حضارة مفقودة"],
    ["marriage", "Marriage", "الزواج"],
    ["otaku-culture", "Otaku Culture", "ثقافة الأوتاكو"],
    ["overpowered-protagonist", "Overpowered Protagonist", "بطل فائق القوة"],
    ["pirates", "Pirates", "القراصنة"],
    ["regret", "Regret", "الندم"],
    ["slavery", "Slavery", "العبودية"],
    ["vikings", "Vikings", "الفايكنغ"],
    ["virtual-world", "Virtual World", "عالم افتراضي"],
    ["writing", "Writing", "الكتابة"],
    ["immortality", "Immortality", "الخلود"],
    ["virtual-reality", "Virtual Reality", "الواقع الافتراضي"],
    ["medicine", "Medicine", "الطب"],
    ["time-loop", "Time Loop", "حلقة زمنية"],
    ["transported-to-another-world", "Transported to Another World", "الانتقال إلى عالم آخر"],
    ["parallel-worlds", "Parallel Worlds", "عوالم متوازية"],
    ["superheroes", "Superheroes", "الأبطال الخارقون"],
  ],
} as const;

type Definition = readonly (readonly [string, string, string])[];
export type TaxonomyVocabulary = keyof typeof taxonomy;
export type TaxonomySlug<V extends TaxonomyVocabulary> = (typeof taxonomy)[V][number][0];

export function taxonomySchema<V extends TaxonomyVocabulary>(vocabulary: V) {
  const values = taxonomy[vocabulary].map(([slug]) => slug) as [
    TaxonomySlug<V>,
    ...TaxonomySlug<V>[],
  ];
  return z.enum(values);
}

export function taxonomySeeds() {
  return (Object.entries(taxonomy) as [TaxonomyVocabulary, Definition][]).flatMap(
    ([vocabulary, values]) =>
      values.map(([slug, labelEn, labelAr], position) => ({
        vocabulary,
        slug,
        labelEn,
        labelAr,
        position,
      })),
  );
}
