use axum::{
    Json, Router,
    extract::{Path, Query, Request, State},
    http::StatusCode,
    middleware,
    response::{IntoResponse, Response},
    routing::{get, post},
};
use serde::{Deserialize, Serialize};
use serde_json::{Value, json};
use sqlx::{AssertSqlSafe, PgPool, types::Json as SqlJson};

#[derive(Clone)]
struct DatabaseState {
    pool: PgPool,
    token: Option<String>,
}
#[derive(Debug)]
pub struct ApiError(StatusCode, String);
impl IntoResponse for ApiError {
    fn into_response(self) -> Response {
        (self.0, Json(json!({"message":self.1}))).into_response()
    }
}
impl From<sqlx::Error> for ApiError {
    fn from(error: sqlx::Error) -> Self {
        let message = if let sqlx::Error::Database(db) = &error {
            format!("تعذّر تطبيق العملية: {}", db.message())
        } else {
            "تعذّر الوصول إلى قاعدة البيانات".to_owned()
        };
        Self(StatusCode::UNPROCESSABLE_ENTITY, message)
    }
}
type ApiResult<T> = Result<T, ApiError>;

pub fn routes(pool: PgPool, token: Option<String>) -> Router {
    let state = DatabaseState { pool, token };
    Router::new()
        .route("/api/database/status", get(database_status))
        .route("/api/database/schema", get(schema))
        .route(
            "/api/database/{table}",
            get(records)
                .post(create_record)
                .patch(update_record)
                .delete(delete_record),
        )
        .route("/api/database/restore", post(restore_record))
        .route_layer(middleware::from_fn_with_state(state.clone(), authorize))
        .with_state(state)
}
async fn authorize(
    State(state): State<DatabaseState>,
    request: Request,
    next: middleware::Next,
) -> Response {
    let allowed = cfg!(debug_assertions)
        && state.token.as_ref().is_some_and(|token| {
            request
                .headers()
                .get("x-nahhasio-admin")
                .and_then(|value| value.to_str().ok())
                .is_some_and(|value| value == token)
        });
    if !allowed {
        return ApiError(
            StatusCode::FORBIDDEN,
            "إدارة البيانات المحلية غير مفعّلة".into(),
        )
        .into_response();
    }
    next.run(request).await
}
#[derive(Clone, Deserialize, Serialize)]
struct Column {
    name: String,
    data_type: String,
    nullable: bool,
    primary: bool,
    generated: bool,
    default_value: Option<String>,
    enum_values: Value,
}
#[derive(Clone, Deserialize, Serialize)]
struct Table {
    name: String,
    columns: Vec<Column>,
    writable: bool,
}
fn writable(name: &str) -> bool {
    !name.starts_with("auth_")
        && !matches!(
            name,
            "audit_logs" | "editorial_revisions" | "background_jobs"
        )
}
// Dynamic SQL below uses only schema-validated, quoted identifiers. Every record value is bound.
// Reference-check SQL is generated by PostgreSQL format(%L) from its constraint catalog.
fn quote(value: &str) -> String {
    format!("\"{}\"", value.replace('"', "\"\""))
}
async fn load_schema(pool: &PgPool) -> ApiResult<Vec<Table>> {
    let values=sqlx::query_scalar::<_,SqlJson<Value>>(r#"select jsonb_build_object('name',t.table_name,'columns',(select jsonb_agg(jsonb_build_object('name',c.column_name,'data_type',c.udt_name,'nullable',c.is_nullable='YES','generated',c.is_generated<>'NEVER','default_value',c.column_default,'primary',exists(select 1 from information_schema.key_column_usage k join information_schema.table_constraints x on x.constraint_name=k.constraint_name and x.table_schema=k.table_schema where k.table_schema='public' and k.table_name=c.table_name and k.column_name=c.column_name and x.constraint_type='PRIMARY KEY'),'enum_values',coalesce((select jsonb_agg(e.enumlabel order by e.enumsortorder) from pg_enum e join pg_type p on p.oid=e.enumtypid where p.typname=c.udt_name),'[]'::jsonb)) order by c.ordinal_position) from information_schema.columns c where c.table_schema='public' and c.table_name=t.table_name),'writable',true) from information_schema.tables t where t.table_schema='public' and t.table_type='BASE TABLE' order by t.table_name"#).fetch_all(pool).await?;
    values
        .into_iter()
        .map(|value| {
            let mut table: Table = serde_json::from_value(value.0)
                .map_err(|_| ApiError(StatusCode::INTERNAL_SERVER_ERROR, "مخطط غير صالح".into()))?;
            table.writable = writable(&table.name);
            Ok(table)
        })
        .collect()
}
async fn database_status(State(state): State<DatabaseState>) -> ApiResult<Json<Value>> {
    let database = sqlx::query_scalar::<_, String>("select current_database()")
        .fetch_one(&state.pool)
        .await?;
    Ok(Json(json!({"database":database})))
}
async fn schema(State(state): State<DatabaseState>) -> ApiResult<Json<Vec<Table>>> {
    Ok(Json(load_schema(&state.pool).await?))
}
async fn table(pool: &PgPool, name: &str) -> ApiResult<Table> {
    load_schema(pool)
        .await?
        .into_iter()
        .find(|table| table.name == name)
        .ok_or_else(|| ApiError(StatusCode::NOT_FOUND, "الجدول غير موجود".into()))
}
#[derive(Deserialize)]
struct Page {
    #[serde(default)]
    offset: u32,
    limit: Option<u32>,
    search: Option<String>,
    filters: Option<String>,
}
async fn records(
    State(state): State<DatabaseState>,
    Path(name): Path<String>,
    Query(page): Query<Page>,
) -> ApiResult<Json<Value>> {
    let meta = table(&state.pool, &name).await?;
    let filter: Value = page
        .filters
        .as_deref()
        .map(serde_json::from_str)
        .transpose()
        .map_err(|_| ApiError(StatusCode::BAD_REQUEST, "مرشحات غير صالحة".into()))?
        .unwrap_or(json!({}));
    if !filter.is_object() {
        return Err(ApiError(
            StatusCode::BAD_REQUEST,
            "المرشحات يجب أن تكون كائناً".into(),
        ));
    }
    let search = format!(
        "%{}%",
        page.search
            .unwrap_or_default()
            .replace('%', "\\%")
            .replace('_', "\\_")
    );
    let source = format!("public.{}", quote(&name));
    let secret: Vec<String> = meta
        .columns
        .iter()
        .filter(|column| {
            (name == "auth_verifications" && column.name == "value")
                || column.name.contains("password")
                || column.name.contains("token")
                || column.name.contains("secret")
        })
        .map(|column| column.name.clone())
        .collect();
    let ordering = meta
        .columns
        .iter()
        .filter(|column| column.primary)
        .map(|column| format!("t.{}", quote(&column.name)))
        .collect::<Vec<_>>()
        .join(",");
    let order = if ordering.is_empty() {
        "to_jsonb(t)::text".to_owned()
    } else {
        ordering
    };
    let query = format!(
        "select to_jsonb(t)-$3::text[] from {source} t where to_jsonb(t) @> $1::jsonb and to_jsonb(t)::text ilike $2 order by {order} limit $4 offset $5"
    );
    let rows = sqlx::query_scalar::<_, SqlJson<Value>>(AssertSqlSafe(query))
        .bind(SqlJson(filter.clone()))
        .bind(&search)
        .bind(secret)
        .bind(i64::from(page.limit.unwrap_or(30).clamp(1, 100)))
        .bind(i64::from(page.offset))
        .fetch_all(&state.pool)
        .await?;
    let count=sqlx::query_scalar::<_,i64>(AssertSqlSafe(format!("select count(*) from {source} t where to_jsonb(t) @> $1::jsonb and to_jsonb(t)::text ilike $2"))).bind(SqlJson(filter)).bind(&search).fetch_one(&state.pool).await?;
    Ok(Json(
        json!({"table":meta,"rows":rows.into_iter().map(|row|row.0).collect::<Vec<_>>(),"total":count,"offset":page.offset}),
    ))
}
#[derive(Deserialize)]
struct Mutation {
    #[serde(default)]
    values: Value,
    #[serde(default)]
    key: Value,
    original: Option<Value>,
}
fn validate_values(meta: &Table, values: &Value, updating: bool) -> ApiResult<Vec<String>> {
    if !meta.writable {
        return Err(ApiError(
            StatusCode::FORBIDDEN,
            "هذا الجدول محمي من التحرير المباشر".into(),
        ));
    }
    let object = values.as_object().ok_or_else(|| {
        ApiError(
            StatusCode::BAD_REQUEST,
            "قيم السجل يجب أن تكون كائناً".into(),
        )
    })?;
    if object.is_empty() {
        return Err(ApiError(StatusCode::BAD_REQUEST, "السجل فارغ".into()));
    }
    for name in object.keys() {
        if !meta.columns.iter().any(|column| {
            column.name == *name && !column.generated && (!updating || !column.primary)
        }) {
            return Err(ApiError(
                StatusCode::BAD_REQUEST,
                format!("الحقل {name} غير قابل للتحرير"),
            ));
        }
    }
    Ok(object.keys().cloned().collect())
}
fn key_condition(meta: &Table, key: &Value) -> ApiResult<String> {
    let object = key
        .as_object()
        .ok_or_else(|| ApiError(StatusCode::BAD_REQUEST, "مفتاح السجل غير صالح".into()))?;
    let primary: Vec<_> = meta
        .columns
        .iter()
        .filter(|column| column.primary)
        .collect();
    if primary.is_empty()
        || primary
            .iter()
            .any(|column| !object.contains_key(&column.name))
    {
        return Err(ApiError(
            StatusCode::BAD_REQUEST,
            "مفتاح السجل غير مكتمل".into(),
        ));
    }
    Ok(primary
        .iter()
        .map(|column| {
            format!(
                "t.{} is not distinct from (jsonb_populate_record(null::public.{},$1::jsonb)).{}",
                quote(&column.name),
                quote(&meta.name),
                quote(&column.name)
            )
        })
        .collect::<Vec<_>>()
        .join(" and "))
}
async fn audit(
    transaction: &mut sqlx::Transaction<'_, sqlx::Postgres>,
    name: &str,
    action: &str,
    before: &Value,
    after: &Value,
) -> ApiResult<()> {
    sqlx::query("insert into audit_logs(action,target_type,target_id,summary,changes) values($1,$2,$3,$4,$5)").bind(format!("local.{action}")).bind(name).bind(after.get("id").or_else(||before.get("id")).map(Value::to_string)).bind("Local dashboard administration").bind(SqlJson(json!({"before":before,"after":after}))).execute(&mut **transaction).await?;
    Ok(())
}
async fn create_record(
    State(state): State<DatabaseState>,
    Path(name): Path<String>,
    Json(input): Json<Mutation>,
) -> ApiResult<Json<Value>> {
    let meta = table(&state.pool, &name).await?;
    let columns = validate_values(&meta, &input.values, false)?;
    let names = columns
        .iter()
        .map(|name| quote(name))
        .collect::<Vec<_>>()
        .join(",");
    let query = format!(
        "insert into public.{} ({names}) select {names} from jsonb_populate_record(null::public.{},$1::jsonb) returning to_jsonb({})",
        quote(&name),
        quote(&name),
        quote(&name)
    );
    let mut transaction = state.pool.begin().await?;
    sqlx::query("SET TRANSACTION READ WRITE")
        .execute(&mut *transaction)
        .await?;
    let row = sqlx::query_scalar::<_, SqlJson<Value>>(AssertSqlSafe(query))
        .bind(SqlJson(input.values))
        .fetch_one(&mut *transaction)
        .await?
        .0;
    audit(&mut transaction, &name, "create", &Value::Null, &row).await?;
    transaction.commit().await?;
    Ok(Json(row))
}
async fn update_record(
    State(state): State<DatabaseState>,
    Path(name): Path<String>,
    Json(input): Json<Mutation>,
) -> ApiResult<Json<Value>> {
    let meta = table(&state.pool, &name).await?;
    let columns = validate_values(&meta, &input.values, true)?;
    let condition = key_condition(&meta, &input.key)?;
    let original = input
        .original
        .ok_or_else(|| ApiError(StatusCode::BAD_REQUEST, "النسخة الأصلية مطلوبة".into()))?;
    let mut transaction = state.pool.begin().await?;
    sqlx::query("SET TRANSACTION READ WRITE")
        .execute(&mut *transaction)
        .await?;
    let current=sqlx::query_scalar::<_,SqlJson<Value>>(AssertSqlSafe(format!("select to_jsonb(t) from public.{} t where {condition} and to_jsonb(t)=$2::jsonb for update",quote(&name)))).bind(SqlJson(input.key.clone())).bind(SqlJson(original)).fetch_optional(&mut *transaction).await?.ok_or_else(||ApiError(StatusCode::CONFLICT,"تغيّر السجل؛ حدّث الصفحة قبل الحفظ".into()))?.0;
    let assignments = columns
        .iter()
        .map(|column| {
            format!(
                "{}=(jsonb_populate_record(null::public.{},$2::jsonb)).{}",
                quote(column),
                quote(&name),
                quote(column)
            )
        })
        .collect::<Vec<_>>()
        .join(",");
    let row = sqlx::query_scalar::<_, SqlJson<Value>>(AssertSqlSafe(format!(
        "update public.{} t set {assignments} where {condition} returning to_jsonb(t)",
        quote(&name)
    )))
    .bind(SqlJson(input.key))
    .bind(SqlJson(input.values))
    .fetch_one(&mut *transaction)
    .await?
    .0;
    audit(&mut transaction, &name, "update", &current, &row).await?;
    transaction.commit().await?;
    Ok(Json(row))
}
async fn delete_record(
    State(state): State<DatabaseState>,
    Path(name): Path<String>,
    Json(input): Json<Mutation>,
) -> ApiResult<Json<Value>> {
    let meta = table(&state.pool, &name).await?;
    if !meta.writable {
        return Err(ApiError(StatusCode::FORBIDDEN, "الجدول محمي".into()));
    }
    let condition = key_condition(&meta, &input.key)?;
    let mut transaction = state.pool.begin().await?;
    sqlx::query("SET TRANSACTION READ WRITE")
        .execute(&mut *transaction)
        .await?;
    let current=sqlx::query_scalar::<_,SqlJson<Value>>(AssertSqlSafe(format!("select to_jsonb(t) from public.{} t where {condition} and to_jsonb(t)=$2::jsonb for update",quote(&name)))).bind(SqlJson(input.key.clone())).bind(SqlJson(input.original.ok_or_else(||ApiError(StatusCode::BAD_REQUEST,"النسخة الأصلية مطلوبة".into()))?)).fetch_optional(&mut *transaction).await?.ok_or_else(||ApiError(StatusCode::CONFLICT,"تغيّر السجل؛ حدّث الصفحة".into()))?.0;
    let references=sqlx::query_scalar::<_,String>("select format('select exists(select 1 from %s child where %s)',c.conrelid::regclass,string_agg(format('to_jsonb(child)->%L is not distinct from $1::jsonb->%L',a.attname,b.attname),' and ')) from pg_constraint c join unnest(c.conkey,c.confkey) as keys(a,b) on true join pg_attribute a on a.attrelid=c.conrelid and a.attnum=keys.a join pg_attribute b on b.attrelid=c.confrelid and b.attnum=keys.b where c.contype='f' and c.confrelid=to_regclass($1) group by c.oid,c.conrelid").bind(format!("public.{}",quote(&name))).fetch_all(&mut *transaction).await?;
    for query in references {
        if sqlx::query_scalar::<_, bool>(AssertSqlSafe(query))
            .bind(SqlJson(current.clone()))
            .fetch_one(&mut *transaction)
            .await?
        {
            return Err(ApiError(
                StatusCode::CONFLICT,
                "للسجل بيانات مرتبطة؛ الحذف المتسلسل غير مسموح".into(),
            ));
        }
    }
    audit(&mut transaction, &name, "delete", &current, &Value::Null).await?;
    sqlx::query(AssertSqlSafe(format!(
        "delete from public.{} t where {condition}",
        quote(&name)
    )))
    .bind(SqlJson(input.key))
    .execute(&mut *transaction)
    .await?;
    transaction.commit().await?;
    Ok(Json(json!({"deleted":true})))
}
#[derive(Deserialize)]
struct Restore {
    audit_id: String,
}
async fn restore_record(
    State(state): State<DatabaseState>,
    Json(input): Json<Restore>,
) -> ApiResult<Json<Value>> {
    let mut transaction = state.pool.begin().await?;
    sqlx::query("SET TRANSACTION READ WRITE")
        .execute(&mut *transaction)
        .await?;
    let snapshot=sqlx::query_scalar::<_,SqlJson<Value>>("select jsonb_build_object('table',target_type,'row',changes->'before') from audit_logs where id::text=$1 and action='local.delete' for update").bind(input.audit_id).fetch_optional(&mut *transaction).await?.ok_or_else(||ApiError(StatusCode::NOT_FOUND,"نسخة الاستعادة غير موجودة".into()))?.0;
    let name = snapshot
        .get("table")
        .and_then(Value::as_str)
        .ok_or_else(|| ApiError(StatusCode::BAD_REQUEST, "نسخة غير صالحة".into()))?;
    let meta = table(&state.pool, name).await?;
    let row = snapshot.get("row").cloned().unwrap_or(Value::Null);
    let columns = validate_values(&meta, &row, false)?;
    let names = columns
        .iter()
        .map(|name| quote(name))
        .collect::<Vec<_>>()
        .join(",");
    let restored=sqlx::query_scalar::<_,SqlJson<Value>>(AssertSqlSafe(format!("insert into public.{} ({names}) select {names} from jsonb_populate_record(null::public.{},$1::jsonb) returning to_jsonb({})",quote(name),quote(name),quote(name)))).bind(SqlJson(row)).fetch_one(&mut *transaction).await?.0;
    audit(&mut transaction, name, "restore", &Value::Null, &restored).await?;
    transaction.commit().await?;
    Ok(Json(restored))
}
