/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as EntitiesRouteImport } from './routes/entities'
import { Route as LineageRouteImport } from './routes/lineage'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as PlanetsRouteImport } from './routes/planets'
import { Route as ProfilesRouteImport } from './routes/profiles'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StudiosRouteImport } from './routes/studios'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCatalogRouteImport } from './routes/admin.catalog'
import { Route as AdminPeopleRouteImport } from './routes/admin.people'
import { Route as AdminPlanetsRouteImport } from './routes/admin.planets'
import { Route as AdminProfilesRouteImport } from './routes/admin.profiles'
import { Route as AdminRelationshipsRouteImport } from './routes/admin.relationships'
import { Route as AdminStudiosRouteImport } from './routes/admin.studios'
import { Route as AdminValidationRouteImport } from './routes/admin.validation'
import { Route as EntitiesIndexRouteImport } from './routes/entities.index'
import { Route as EntitiesEntityIdRouteImport } from './routes/entities.$entityId'
import { Route as PeopleIndexRouteImport } from './routes/people.index'
import { Route as PeoplePersonIdRouteImport } from './routes/people.$personId'
import { Route as PlanetsIndexRouteImport } from './routes/planets.index'
import { Route as PlanetsPlanetSlugRouteImport } from './routes/planets.$planetSlug'
import { Route as StudiosIndexRouteImport } from './routes/studios.index'
import { Route as StudiosStudioIdRouteImport } from './routes/studios.$studioId'
import { Route as TitlesTitleIdRouteImport } from './routes/titles.$titleId'
import { Route as AdminCatalogIndexRouteImport } from './routes/admin.catalog.index'
import { Route as AdminCatalogWorkIdRouteImport } from './routes/admin.catalog.$workId'
import { Route as AdminCatalogNewRouteImport } from './routes/admin.catalog_.new'
import { Route as TitlesTitleIdInstallmentsInstallmentIdRouteImport } from './routes/titles_.$titleId.installments.$installmentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesRoute = EntitiesRouteImport.update({
  id: '/entities',
  path: '/entities',
  getParentRoute: () => rootRouteImport,
} as any)
const LineageRoute = LineageRouteImport.update({
  id: '/lineage',
  path: '/lineage',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanetsRoute = PlanetsRouteImport.update({
  id: '/planets',
  path: '/planets',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesRoute = ProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StudiosRoute = StudiosRouteImport.update({
  id: '/studios',
  path: '/studios',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogRoute = AdminCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPeopleRoute = AdminPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlanetsRoute = AdminPlanetsRouteImport.update({
  id: '/planets',
  path: '/planets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfilesRoute = AdminProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRelationshipsRoute = AdminRelationshipsRouteImport.update({
  id: '/relationships',
  path: '/relationships',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudiosRoute = AdminStudiosRouteImport.update({
  id: '/studios',
  path: '/studios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminValidationRoute = AdminValidationRouteImport.update({
  id: '/validation',
  path: '/validation',
  getParentRoute: () => AdminRoute,
} as any)
const EntitiesIndexRoute = EntitiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EntitiesRoute,
} as any)
const EntitiesEntityIdRoute = EntitiesEntityIdRouteImport.update({
  id: '/$entityId',
  path: '/$entityId',
  getParentRoute: () => EntitiesRoute,
} as any)
const PeopleIndexRoute = PeopleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PeopleRoute,
} as any)
const PeoplePersonIdRoute = PeoplePersonIdRouteImport.update({
  id: '/$personId',
  path: '/$personId',
  getParentRoute: () => PeopleRoute,
} as any)
const PlanetsIndexRoute = PlanetsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlanetsRoute,
} as any)
const PlanetsPlanetSlugRoute = PlanetsPlanetSlugRouteImport.update({
  id: '/$planetSlug',
  path: '/$planetSlug',
  getParentRoute: () => PlanetsRoute,
} as any)
const StudiosIndexRoute = StudiosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudiosRoute,
} as any)
const StudiosStudioIdRoute = StudiosStudioIdRouteImport.update({
  id: '/$studioId',
  path: '/$studioId',
  getParentRoute: () => StudiosRoute,
} as any)
const TitlesTitleIdRoute = TitlesTitleIdRouteImport.update({
  id: '/titles/$titleId',
  path: '/titles/$titleId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCatalogIndexRoute = AdminCatalogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminCatalogRoute,
} as any)
const AdminCatalogWorkIdRoute = AdminCatalogWorkIdRouteImport.update({
  id: '/$workId',
  path: '/$workId',
  getParentRoute: () => AdminCatalogRoute,
} as any)
const AdminCatalogNewRoute = AdminCatalogNewRouteImport.update({
  id: '/catalog_/new',
  path: '/catalog/new',
  getParentRoute: () => AdminRoute,
} as any)
const TitlesTitleIdInstallmentsInstallmentIdRoute =
  TitlesTitleIdInstallmentsInstallmentIdRouteImport.update({
    id: '/titles_/$titleId/installments/$installmentId',
    path: '/titles/$titleId/installments/$installmentId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/browse': typeof BrowseRoute
  '/compare': typeof CompareRoute
  '/entities': typeof EntitiesRouteWithChildren
  '/lineage': typeof LineageRoute
  '/people': typeof PeopleRouteWithChildren
  '/planets': typeof PlanetsRouteWithChildren
  '/profiles': typeof ProfilesRoute
  '/settings': typeof SettingsRoute
  '/studios': typeof StudiosRouteWithChildren
  '/admin/catalog': typeof AdminCatalogRouteWithChildren
  '/admin/people': typeof AdminPeopleRoute
  '/admin/planets': typeof AdminPlanetsRoute
  '/admin/profiles': typeof AdminProfilesRoute
  '/admin/relationships': typeof AdminRelationshipsRoute
  '/admin/studios': typeof AdminStudiosRoute
  '/admin/validation': typeof AdminValidationRoute
  '/entities/$entityId': typeof EntitiesEntityIdRoute
  '/people/$personId': typeof PeoplePersonIdRoute
  '/planets/$planetSlug': typeof PlanetsPlanetSlugRoute
  '/studios/$studioId': typeof StudiosStudioIdRoute
  '/titles/$titleId': typeof TitlesTitleIdRoute
  '/admin/': typeof AdminIndexRoute
  '/entities/': typeof EntitiesIndexRoute
  '/people/': typeof PeopleIndexRoute
  '/planets/': typeof PlanetsIndexRoute
  '/studios/': typeof StudiosIndexRoute
  '/admin/catalog/$workId': typeof AdminCatalogWorkIdRoute
  '/admin/catalog/new': typeof AdminCatalogNewRoute
  '/admin/catalog/': typeof AdminCatalogIndexRoute
  '/titles/$titleId/installments/$installmentId': typeof TitlesTitleIdInstallmentsInstallmentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/compare': typeof CompareRoute
  '/lineage': typeof LineageRoute
  '/profiles': typeof ProfilesRoute
  '/settings': typeof SettingsRoute
  '/admin/people': typeof AdminPeopleRoute
  '/admin/planets': typeof AdminPlanetsRoute
  '/admin/profiles': typeof AdminProfilesRoute
  '/admin/relationships': typeof AdminRelationshipsRoute
  '/admin/studios': typeof AdminStudiosRoute
  '/admin/validation': typeof AdminValidationRoute
  '/entities/$entityId': typeof EntitiesEntityIdRoute
  '/people/$personId': typeof PeoplePersonIdRoute
  '/planets/$planetSlug': typeof PlanetsPlanetSlugRoute
  '/studios/$studioId': typeof StudiosStudioIdRoute
  '/titles/$titleId': typeof TitlesTitleIdRoute
  '/admin': typeof AdminIndexRoute
  '/entities': typeof EntitiesIndexRoute
  '/people': typeof PeopleIndexRoute
  '/planets': typeof PlanetsIndexRoute
  '/studios': typeof StudiosIndexRoute
  '/admin/catalog/$workId': typeof AdminCatalogWorkIdRoute
  '/admin/catalog/new': typeof AdminCatalogNewRoute
  '/admin/catalog': typeof AdminCatalogIndexRoute
  '/titles/$titleId/installments/$installmentId': typeof TitlesTitleIdInstallmentsInstallmentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/browse': typeof BrowseRoute
  '/compare': typeof CompareRoute
  '/entities': typeof EntitiesRouteWithChildren
  '/lineage': typeof LineageRoute
  '/people': typeof PeopleRouteWithChildren
  '/planets': typeof PlanetsRouteWithChildren
  '/profiles': typeof ProfilesRoute
  '/settings': typeof SettingsRoute
  '/studios': typeof StudiosRouteWithChildren
  '/admin/catalog': typeof AdminCatalogRouteWithChildren
  '/admin/people': typeof AdminPeopleRoute
  '/admin/planets': typeof AdminPlanetsRoute
  '/admin/profiles': typeof AdminProfilesRoute
  '/admin/relationships': typeof AdminRelationshipsRoute
  '/admin/studios': typeof AdminStudiosRoute
  '/admin/validation': typeof AdminValidationRoute
  '/entities/$entityId': typeof EntitiesEntityIdRoute
  '/people/$personId': typeof PeoplePersonIdRoute
  '/planets/$planetSlug': typeof PlanetsPlanetSlugRoute
  '/studios/$studioId': typeof StudiosStudioIdRoute
  '/titles/$titleId': typeof TitlesTitleIdRoute
  '/admin/': typeof AdminIndexRoute
  '/entities/': typeof EntitiesIndexRoute
  '/people/': typeof PeopleIndexRoute
  '/planets/': typeof PlanetsIndexRoute
  '/studios/': typeof StudiosIndexRoute
  '/admin/catalog/$workId': typeof AdminCatalogWorkIdRoute
  '/admin/catalog_/new': typeof AdminCatalogNewRoute
  '/admin/catalog/': typeof AdminCatalogIndexRoute
  '/titles_/$titleId/installments/$installmentId': typeof TitlesTitleIdInstallmentsInstallmentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/browse'
    | '/compare'
    | '/entities'
    | '/lineage'
    | '/people'
    | '/planets'
    | '/profiles'
    | '/settings'
    | '/studios'
    | '/admin/catalog'
    | '/admin/people'
    | '/admin/planets'
    | '/admin/profiles'
    | '/admin/relationships'
    | '/admin/studios'
    | '/admin/validation'
    | '/entities/$entityId'
    | '/people/$personId'
    | '/planets/$planetSlug'
    | '/studios/$studioId'
    | '/titles/$titleId'
    | '/admin/'
    | '/entities/'
    | '/people/'
    | '/planets/'
    | '/studios/'
    | '/admin/catalog/$workId'
    | '/admin/catalog/new'
    | '/admin/catalog/'
    | '/titles/$titleId/installments/$installmentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse'
    | '/compare'
    | '/lineage'
    | '/profiles'
    | '/settings'
    | '/admin/people'
    | '/admin/planets'
    | '/admin/profiles'
    | '/admin/relationships'
    | '/admin/studios'
    | '/admin/validation'
    | '/entities/$entityId'
    | '/people/$personId'
    | '/planets/$planetSlug'
    | '/studios/$studioId'
    | '/titles/$titleId'
    | '/admin'
    | '/entities'
    | '/people'
    | '/planets'
    | '/studios'
    | '/admin/catalog/$workId'
    | '/admin/catalog/new'
    | '/admin/catalog'
    | '/titles/$titleId/installments/$installmentId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/browse'
    | '/compare'
    | '/entities'
    | '/lineage'
    | '/people'
    | '/planets'
    | '/profiles'
    | '/settings'
    | '/studios'
    | '/admin/catalog'
    | '/admin/people'
    | '/admin/planets'
    | '/admin/profiles'
    | '/admin/relationships'
    | '/admin/studios'
    | '/admin/validation'
    | '/entities/$entityId'
    | '/people/$personId'
    | '/planets/$planetSlug'
    | '/studios/$studioId'
    | '/titles/$titleId'
    | '/admin/'
    | '/entities/'
    | '/people/'
    | '/planets/'
    | '/studios/'
    | '/admin/catalog/$workId'
    | '/admin/catalog_/new'
    | '/admin/catalog/'
    | '/titles_/$titleId/installments/$installmentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BrowseRoute: typeof BrowseRoute
  CompareRoute: typeof CompareRoute
  EntitiesRoute: typeof EntitiesRouteWithChildren
  LineageRoute: typeof LineageRoute
  PeopleRoute: typeof PeopleRouteWithChildren
  PlanetsRoute: typeof PlanetsRouteWithChildren
  ProfilesRoute: typeof ProfilesRoute
  SettingsRoute: typeof SettingsRoute
  StudiosRoute: typeof StudiosRouteWithChildren
  TitlesTitleIdRoute: typeof TitlesTitleIdRoute
  TitlesTitleIdInstallmentsInstallmentIdRoute: typeof TitlesTitleIdInstallmentsInstallmentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities': {
      id: '/entities'
      path: '/entities'
      fullPath: '/entities'
      preLoaderRoute: typeof EntitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lineage': {
      id: '/lineage'
      path: '/lineage'
      fullPath: '/lineage'
      preLoaderRoute: typeof LineageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planets': {
      id: '/planets'
      path: '/planets'
      fullPath: '/planets'
      preLoaderRoute: typeof PlanetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles': {
      id: '/profiles'
      path: '/profiles'
      fullPath: '/profiles'
      preLoaderRoute: typeof ProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studios': {
      id: '/studios'
      path: '/studios'
      fullPath: '/studios'
      preLoaderRoute: typeof StudiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalog': {
      id: '/admin/catalog'
      path: '/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AdminCatalogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/people': {
      id: '/admin/people'
      path: '/people'
      fullPath: '/admin/people'
      preLoaderRoute: typeof AdminPeopleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/planets': {
      id: '/admin/planets'
      path: '/planets'
      fullPath: '/admin/planets'
      preLoaderRoute: typeof AdminPlanetsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profiles': {
      id: '/admin/profiles'
      path: '/profiles'
      fullPath: '/admin/profiles'
      preLoaderRoute: typeof AdminProfilesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/relationships': {
      id: '/admin/relationships'
      path: '/relationships'
      fullPath: '/admin/relationships'
      preLoaderRoute: typeof AdminRelationshipsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/studios': {
      id: '/admin/studios'
      path: '/studios'
      fullPath: '/admin/studios'
      preLoaderRoute: typeof AdminStudiosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/validation': {
      id: '/admin/validation'
      path: '/validation'
      fullPath: '/admin/validation'
      preLoaderRoute: typeof AdminValidationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/entities/': {
      id: '/entities/'
      path: '/'
      fullPath: '/entities/'
      preLoaderRoute: typeof EntitiesIndexRouteImport
      parentRoute: typeof EntitiesRoute
    }
    '/entities/$entityId': {
      id: '/entities/$entityId'
      path: '/$entityId'
      fullPath: '/entities/$entityId'
      preLoaderRoute: typeof EntitiesEntityIdRouteImport
      parentRoute: typeof EntitiesRoute
    }
    '/people/': {
      id: '/people/'
      path: '/'
      fullPath: '/people/'
      preLoaderRoute: typeof PeopleIndexRouteImport
      parentRoute: typeof PeopleRoute
    }
    '/people/$personId': {
      id: '/people/$personId'
      path: '/$personId'
      fullPath: '/people/$personId'
      preLoaderRoute: typeof PeoplePersonIdRouteImport
      parentRoute: typeof PeopleRoute
    }
    '/planets/': {
      id: '/planets/'
      path: '/'
      fullPath: '/planets/'
      preLoaderRoute: typeof PlanetsIndexRouteImport
      parentRoute: typeof PlanetsRoute
    }
    '/planets/$planetSlug': {
      id: '/planets/$planetSlug'
      path: '/$planetSlug'
      fullPath: '/planets/$planetSlug'
      preLoaderRoute: typeof PlanetsPlanetSlugRouteImport
      parentRoute: typeof PlanetsRoute
    }
    '/studios/': {
      id: '/studios/'
      path: '/'
      fullPath: '/studios/'
      preLoaderRoute: typeof StudiosIndexRouteImport
      parentRoute: typeof StudiosRoute
    }
    '/studios/$studioId': {
      id: '/studios/$studioId'
      path: '/$studioId'
      fullPath: '/studios/$studioId'
      preLoaderRoute: typeof StudiosStudioIdRouteImport
      parentRoute: typeof StudiosRoute
    }
    '/titles/$titleId': {
      id: '/titles/$titleId'
      path: '/titles/$titleId'
      fullPath: '/titles/$titleId'
      preLoaderRoute: typeof TitlesTitleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/catalog/': {
      id: '/admin/catalog/'
      path: '/'
      fullPath: '/admin/catalog/'
      preLoaderRoute: typeof AdminCatalogIndexRouteImport
      parentRoute: typeof AdminCatalogRoute
    }
    '/admin/catalog/$workId': {
      id: '/admin/catalog/$workId'
      path: '/$workId'
      fullPath: '/admin/catalog/$workId'
      preLoaderRoute: typeof AdminCatalogWorkIdRouteImport
      parentRoute: typeof AdminCatalogRoute
    }
    '/admin/catalog_/new': {
      id: '/admin/catalog_/new'
      path: '/catalog/new'
      fullPath: '/admin/catalog/new'
      preLoaderRoute: typeof AdminCatalogNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/titles_/$titleId/installments/$installmentId': {
      id: '/titles_/$titleId/installments/$installmentId'
      path: '/titles/$titleId/installments/$installmentId'
      fullPath: '/titles/$titleId/installments/$installmentId'
      preLoaderRoute: typeof TitlesTitleIdInstallmentsInstallmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminCatalogRouteChildren {
  AdminCatalogWorkIdRoute: typeof AdminCatalogWorkIdRoute
  AdminCatalogIndexRoute: typeof AdminCatalogIndexRoute
}

const AdminCatalogRouteChildren: AdminCatalogRouteChildren = {
  AdminCatalogWorkIdRoute: AdminCatalogWorkIdRoute,
  AdminCatalogIndexRoute: AdminCatalogIndexRoute,
}

const AdminCatalogRouteWithChildren = AdminCatalogRoute._addFileChildren(
  AdminCatalogRouteChildren,
)

interface AdminRouteChildren {
  AdminCatalogRoute: typeof AdminCatalogRouteWithChildren
  AdminPeopleRoute: typeof AdminPeopleRoute
  AdminPlanetsRoute: typeof AdminPlanetsRoute
  AdminProfilesRoute: typeof AdminProfilesRoute
  AdminRelationshipsRoute: typeof AdminRelationshipsRoute
  AdminStudiosRoute: typeof AdminStudiosRoute
  AdminValidationRoute: typeof AdminValidationRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCatalogNewRoute: typeof AdminCatalogNewRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCatalogRoute: AdminCatalogRouteWithChildren,
  AdminPeopleRoute: AdminPeopleRoute,
  AdminPlanetsRoute: AdminPlanetsRoute,
  AdminProfilesRoute: AdminProfilesRoute,
  AdminRelationshipsRoute: AdminRelationshipsRoute,
  AdminStudiosRoute: AdminStudiosRoute,
  AdminValidationRoute: AdminValidationRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCatalogNewRoute: AdminCatalogNewRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EntitiesRouteChildren {
  EntitiesEntityIdRoute: typeof EntitiesEntityIdRoute
  EntitiesIndexRoute: typeof EntitiesIndexRoute
}

const EntitiesRouteChildren: EntitiesRouteChildren = {
  EntitiesEntityIdRoute: EntitiesEntityIdRoute,
  EntitiesIndexRoute: EntitiesIndexRoute,
}

const EntitiesRouteWithChildren = EntitiesRoute._addFileChildren(
  EntitiesRouteChildren,
)

interface PeopleRouteChildren {
  PeoplePersonIdRoute: typeof PeoplePersonIdRoute
  PeopleIndexRoute: typeof PeopleIndexRoute
}

const PeopleRouteChildren: PeopleRouteChildren = {
  PeoplePersonIdRoute: PeoplePersonIdRoute,
  PeopleIndexRoute: PeopleIndexRoute,
}

const PeopleRouteWithChildren =
  PeopleRoute._addFileChildren(PeopleRouteChildren)

interface PlanetsRouteChildren {
  PlanetsPlanetSlugRoute: typeof PlanetsPlanetSlugRoute
  PlanetsIndexRoute: typeof PlanetsIndexRoute
}

const PlanetsRouteChildren: PlanetsRouteChildren = {
  PlanetsPlanetSlugRoute: PlanetsPlanetSlugRoute,
  PlanetsIndexRoute: PlanetsIndexRoute,
}

const PlanetsRouteWithChildren =
  PlanetsRoute._addFileChildren(PlanetsRouteChildren)

interface StudiosRouteChildren {
  StudiosStudioIdRoute: typeof StudiosStudioIdRoute
  StudiosIndexRoute: typeof StudiosIndexRoute
}

const StudiosRouteChildren: StudiosRouteChildren = {
  StudiosStudioIdRoute: StudiosStudioIdRoute,
  StudiosIndexRoute: StudiosIndexRoute,
}

const StudiosRouteWithChildren =
  StudiosRoute._addFileChildren(StudiosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BrowseRoute: BrowseRoute,
  CompareRoute: CompareRoute,
  EntitiesRoute: EntitiesRouteWithChildren,
  LineageRoute: LineageRoute,
  PeopleRoute: PeopleRouteWithChildren,
  PlanetsRoute: PlanetsRouteWithChildren,
  ProfilesRoute: ProfilesRoute,
  SettingsRoute: SettingsRoute,
  StudiosRoute: StudiosRouteWithChildren,
  TitlesTitleIdRoute: TitlesTitleIdRoute,
  TitlesTitleIdInstallmentsInstallmentIdRoute:
    TitlesTitleIdInstallmentsInstallmentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
