/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DatabaseRouteImport } from './routes/database'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ServerRouteImport } from './routes/server'
import { Route as DatabaseIndexRouteImport } from './routes/database.index'
import { Route as DatabaseCollectionRouteImport } from './routes/database.$collection'
import { Route as DatabaseGraphRouteImport } from './routes/database.graph'
import { Route as DatabaseImagesRouteImport } from './routes/database.images'
import { Route as DatabaseImportsRouteImport } from './routes/database.imports'
import { Route as DatabaseJsonRouteImport } from './routes/database.json'
import { Route as DatabaseRevisionsRouteImport } from './routes/database.revisions'
import { Route as DatabaseTablesRouteImport } from './routes/database.tables'
import { Route as DatabaseValidationRouteImport } from './routes/database.validation'
import { Route as MediaSplatRouteImport } from './routes/media.$'
import { Route as ServerSectionRouteImport } from './routes/server.$section'
import { Route as DatabaseWorksNewRouteImport } from './routes/database.works.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatabaseRoute = DatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerRoute = ServerRouteImport.update({
  id: '/server',
  path: '/server',
  getParentRoute: () => rootRouteImport,
} as any)
const DatabaseIndexRoute = DatabaseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DatabaseRoute,
} as any)
const DatabaseCollectionRoute = DatabaseCollectionRouteImport.update({
  id: '/$collection',
  path: '/$collection',
  getParentRoute: () => DatabaseRoute,
} as any)
const DatabaseGraphRoute = DatabaseGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => DatabaseRoute,
} as any)
const DatabaseImagesRoute = DatabaseImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => DatabaseRoute,
} as any)
const DatabaseImportsRoute = DatabaseImportsRouteImport.update({
  id: '/imports',
  path: '/imports',
  getParentRoute: () => DatabaseRoute,
} as any)
const DatabaseJsonRoute = DatabaseJsonRouteImport.update({
  id: '/json',
  path: '/json',
  getParentRoute: () => DatabaseRoute,
} as any)
const DatabaseRevisionsRoute = DatabaseRevisionsRouteImport.update({
  id: '/revisions',
  path: '/revisions',
  getParentRoute: () => DatabaseRoute,
} as any)
const DatabaseTablesRoute = DatabaseTablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => DatabaseRoute,
} as any)
const DatabaseValidationRoute = DatabaseValidationRouteImport.update({
  id: '/validation',
  path: '/validation',
  getParentRoute: () => DatabaseRoute,
} as any)
const MediaSplatRoute = MediaSplatRouteImport.update({
  id: '/media/$',
  path: '/media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerSectionRoute = ServerSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => ServerRoute,
} as any)
const DatabaseWorksNewRoute = DatabaseWorksNewRouteImport.update({
  id: '/works/new',
  path: '/works/new',
  getParentRoute: () => DatabaseRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/database': typeof DatabaseRouteWithChildren
  '/login': typeof LoginRoute
  '/server': typeof ServerRouteWithChildren
  '/database/$collection': typeof DatabaseCollectionRoute
  '/database/graph': typeof DatabaseGraphRoute
  '/database/images': typeof DatabaseImagesRoute
  '/database/imports': typeof DatabaseImportsRoute
  '/database/json': typeof DatabaseJsonRoute
  '/database/revisions': typeof DatabaseRevisionsRoute
  '/database/tables': typeof DatabaseTablesRoute
  '/database/validation': typeof DatabaseValidationRoute
  '/media/$': typeof MediaSplatRoute
  '/server/$section': typeof ServerSectionRoute
  '/database/': typeof DatabaseIndexRoute
  '/database/works/new': typeof DatabaseWorksNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/server': typeof ServerRouteWithChildren
  '/database/$collection': typeof DatabaseCollectionRoute
  '/database/graph': typeof DatabaseGraphRoute
  '/database/images': typeof DatabaseImagesRoute
  '/database/imports': typeof DatabaseImportsRoute
  '/database/json': typeof DatabaseJsonRoute
  '/database/revisions': typeof DatabaseRevisionsRoute
  '/database/tables': typeof DatabaseTablesRoute
  '/database/validation': typeof DatabaseValidationRoute
  '/media/$': typeof MediaSplatRoute
  '/server/$section': typeof ServerSectionRoute
  '/database': typeof DatabaseIndexRoute
  '/database/works/new': typeof DatabaseWorksNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/database': typeof DatabaseRouteWithChildren
  '/login': typeof LoginRoute
  '/server': typeof ServerRouteWithChildren
  '/database/$collection': typeof DatabaseCollectionRoute
  '/database/graph': typeof DatabaseGraphRoute
  '/database/images': typeof DatabaseImagesRoute
  '/database/imports': typeof DatabaseImportsRoute
  '/database/json': typeof DatabaseJsonRoute
  '/database/revisions': typeof DatabaseRevisionsRoute
  '/database/tables': typeof DatabaseTablesRoute
  '/database/validation': typeof DatabaseValidationRoute
  '/media/$': typeof MediaSplatRoute
  '/server/$section': typeof ServerSectionRoute
  '/database/': typeof DatabaseIndexRoute
  '/database/works/new': typeof DatabaseWorksNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/database'
    | '/login'
    | '/server'
    | '/database/$collection'
    | '/database/graph'
    | '/database/images'
    | '/database/imports'
    | '/database/json'
    | '/database/revisions'
    | '/database/tables'
    | '/database/validation'
    | '/media/$'
    | '/server/$section'
    | '/database/'
    | '/database/works/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/server'
    | '/database/$collection'
    | '/database/graph'
    | '/database/images'
    | '/database/imports'
    | '/database/json'
    | '/database/revisions'
    | '/database/tables'
    | '/database/validation'
    | '/media/$'
    | '/server/$section'
    | '/database'
    | '/database/works/new'
  id:
    | '__root__'
    | '/'
    | '/database'
    | '/login'
    | '/server'
    | '/database/$collection'
    | '/database/graph'
    | '/database/images'
    | '/database/imports'
    | '/database/json'
    | '/database/revisions'
    | '/database/tables'
    | '/database/validation'
    | '/media/$'
    | '/server/$section'
    | '/database/'
    | '/database/works/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DatabaseRoute: typeof DatabaseRouteWithChildren
  LoginRoute: typeof LoginRoute
  ServerRoute: typeof ServerRouteWithChildren
  MediaSplatRoute: typeof MediaSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/database': {
      id: '/database'
      path: '/database'
      fullPath: '/database'
      preLoaderRoute: typeof DatabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server': {
      id: '/server'
      path: '/server'
      fullPath: '/server'
      preLoaderRoute: typeof ServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/database/': {
      id: '/database/'
      path: '/'
      fullPath: '/database/'
      preLoaderRoute: typeof DatabaseIndexRouteImport
      parentRoute: typeof DatabaseRoute
    }
    '/database/$collection': {
      id: '/database/$collection'
      path: '/$collection'
      fullPath: '/database/$collection'
      preLoaderRoute: typeof DatabaseCollectionRouteImport
      parentRoute: typeof DatabaseRoute
    }
    '/database/graph': {
      id: '/database/graph'
      path: '/graph'
      fullPath: '/database/graph'
      preLoaderRoute: typeof DatabaseGraphRouteImport
      parentRoute: typeof DatabaseRoute
    }
    '/database/images': {
      id: '/database/images'
      path: '/images'
      fullPath: '/database/images'
      preLoaderRoute: typeof DatabaseImagesRouteImport
      parentRoute: typeof DatabaseRoute
    }
    '/database/imports': {
      id: '/database/imports'
      path: '/imports'
      fullPath: '/database/imports'
      preLoaderRoute: typeof DatabaseImportsRouteImport
      parentRoute: typeof DatabaseRoute
    }
    '/database/json': {
      id: '/database/json'
      path: '/json'
      fullPath: '/database/json'
      preLoaderRoute: typeof DatabaseJsonRouteImport
      parentRoute: typeof DatabaseRoute
    }
    '/database/revisions': {
      id: '/database/revisions'
      path: '/revisions'
      fullPath: '/database/revisions'
      preLoaderRoute: typeof DatabaseRevisionsRouteImport
      parentRoute: typeof DatabaseRoute
    }
    '/database/tables': {
      id: '/database/tables'
      path: '/tables'
      fullPath: '/database/tables'
      preLoaderRoute: typeof DatabaseTablesRouteImport
      parentRoute: typeof DatabaseRoute
    }
    '/database/validation': {
      id: '/database/validation'
      path: '/validation'
      fullPath: '/database/validation'
      preLoaderRoute: typeof DatabaseValidationRouteImport
      parentRoute: typeof DatabaseRoute
    }
    '/media/$': {
      id: '/media/$'
      path: '/media/$'
      fullPath: '/media/$'
      preLoaderRoute: typeof MediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server/$section': {
      id: '/server/$section'
      path: '/$section'
      fullPath: '/server/$section'
      preLoaderRoute: typeof ServerSectionRouteImport
      parentRoute: typeof ServerRoute
    }
    '/database/works/new': {
      id: '/database/works/new'
      path: '/works/new'
      fullPath: '/database/works/new'
      preLoaderRoute: typeof DatabaseWorksNewRouteImport
      parentRoute: typeof DatabaseRoute
    }
  }
}

interface DatabaseRouteChildren {
  DatabaseCollectionRoute: typeof DatabaseCollectionRoute
  DatabaseGraphRoute: typeof DatabaseGraphRoute
  DatabaseImagesRoute: typeof DatabaseImagesRoute
  DatabaseImportsRoute: typeof DatabaseImportsRoute
  DatabaseJsonRoute: typeof DatabaseJsonRoute
  DatabaseRevisionsRoute: typeof DatabaseRevisionsRoute
  DatabaseTablesRoute: typeof DatabaseTablesRoute
  DatabaseValidationRoute: typeof DatabaseValidationRoute
  DatabaseIndexRoute: typeof DatabaseIndexRoute
  DatabaseWorksNewRoute: typeof DatabaseWorksNewRoute
}

const DatabaseRouteChildren: DatabaseRouteChildren = {
  DatabaseCollectionRoute: DatabaseCollectionRoute,
  DatabaseGraphRoute: DatabaseGraphRoute,
  DatabaseImagesRoute: DatabaseImagesRoute,
  DatabaseImportsRoute: DatabaseImportsRoute,
  DatabaseJsonRoute: DatabaseJsonRoute,
  DatabaseRevisionsRoute: DatabaseRevisionsRoute,
  DatabaseTablesRoute: DatabaseTablesRoute,
  DatabaseValidationRoute: DatabaseValidationRoute,
  DatabaseIndexRoute: DatabaseIndexRoute,
  DatabaseWorksNewRoute: DatabaseWorksNewRoute,
}

const DatabaseRouteWithChildren = DatabaseRoute._addFileChildren(
  DatabaseRouteChildren,
)

interface ServerRouteChildren {
  ServerSectionRoute: typeof ServerSectionRoute
}

const ServerRouteChildren: ServerRouteChildren = {
  ServerSectionRoute: ServerSectionRoute,
}

const ServerRouteWithChildren =
  ServerRoute._addFileChildren(ServerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatabaseRoute: DatabaseRouteWithChildren,
  LoginRoute: LoginRoute,
  ServerRoute: ServerRouteWithChildren,
  MediaSplatRoute: MediaSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
