// Only fixed server-owned fragments are interpolated; user input is always bound.
pub(super) const FILTER: &str = r#"
($1::text is null or strpos(lower(t.canonical_title),lower($1))>0 or strpos(lower(coalesce(t.title_ar,'')),lower($1))>0 or exists(select 1 from title_aliases a where a.title_id=t.id and strpos(lower(a.title),lower($1))>0))
and ($2::text is null or t.format::text=$2)
and ($3::text is null or t.audience::text=$3)
and ($4::text is null or exists(select 1 from title_genres tg join genres g on g.id=tg.value_id where tg.title_id=t.id and g.slug=$4))
and ($5::text is null or exists(select 1 from installments i where i.title_id=t.id and i.status::text=$5))
and ($6::integer is null or t.release_year>=$6)
and ($7::integer is null or t.release_year<=$7)
and ($10::boolean or not t.is_private)
and ($11::text is null or exists(select 1 from title_planets tp join planets p on p.id=tp.planet_id where tp.title_id=t.id and p.slug=$11 and p.is_active))
"#;

pub(super) const SUMMARY: &str = r#"jsonb_build_object(
'isPrivate',t.is_private,'id',t.id,'canonicalTitle',t.canonical_title,'titleAr',t.title_ar,'summary',t.summary,
'releaseYear',t.release_year,'format',t.format,'audience',t.audience,'age',t.age,
'installmentCount',(select count(*) from installments i where i.title_id=t.id),
'episodeCount',(select count(*) from episodes e join installments i on i.id=e.installment_id where i.title_id=t.id),
'poster',(select jsonb_build_object('id',a.id,'url','/api/v1/artwork/'||a.id,'mimeType',a.mime_type,'width',a.width,'height',a.height,'byteSize',a.byte_size,'sha256',a.sha256,'originalFilename',a.original_filename,'focalX',a.focal_x,'focalY',a.focal_y) from media_asset_assignments m join media_assets a on a.id=m.asset_id where m.title_id=t.id and m.role='poster' order by m.is_primary desc,m.id limit 1))"#;

pub(super) const DETAIL: &str = r#"jsonb_build_object(
'sortTitle',t.sort_title,'curatorNotes',t.curator_notes,'qualityScore',t.quality_score,'verifiedAt',t.verified_at,'createdAt',t.created_at,'updatedAt',t.updated_at,
'externalReferences',coalesce((select jsonb_agg(jsonb_build_object('id',x.id,'provider',x.provider,'externalId',x.external_id,'url',x.url) order by x.provider,x.id) from external_identities x where x.title_id=t.id),'[]'::jsonb),
'tones',coalesce((select jsonb_agg(jsonb_build_object('id',v.id,'slug',v.slug,'labelEn',v.label_en,'labelAr',v.label_ar,'descriptionEn',v.description_en,'descriptionAr',v.description_ar) order by v.position,v.slug) from title_tones tv join tones v on v.id=tv.value_id where tv.title_id=t.id),'[]'::jsonb),
'tags',coalesce((select jsonb_agg(jsonb_build_object('id',v.id,'slug',v.slug,'labelEn',v.label_en,'labelAr',v.label_ar,'descriptionEn',v.description_en,'descriptionAr',v.description_ar) order by v.position,v.slug) from title_tags tv join tags v on v.id=tv.value_id where tv.title_id=t.id),'[]'::jsonb),
'countries',coalesce((select jsonb_agg(jsonb_build_object('id',v.id,'slug',v.slug,'labelEn',v.label_en,'labelAr',v.label_ar,'descriptionEn',v.description_en,'descriptionAr',v.description_ar) order by v.position,v.slug) from title_countries tv join countries v on v.id=tv.value_id where tv.title_id=t.id),'[]'::jsonb),
'planets',coalesce((select jsonb_agg(jsonb_build_object('id',p.id,'slug',p.slug,'nameAr',p.name_ar,'nameEn',p.name_en,'icon',p.icon,'description',p.description,'primaryColor',p.primary_color,'secondaryColor',p.secondary_color,'featuredRank',tp.featured_rank) order by p.display_order,p.id) from title_planets tp join planets p on p.id=tp.planet_id where tp.title_id=t.id),'[]'::jsonb),
'awards',coalesce((select jsonb_agg(jsonb_build_object('id',r.id,'installmentId',r.installment_id,'organizationSlug',r.organization_slug,'organizationName',r.organization_name,'category',r.category,'year',r.year,'result',r.result,'isFeatured',r.is_featured,'sourceUrl',r.source_url,'notes',r.notes,'position',r.position,'organization',case when org.id is null then null else jsonb_build_object('id',org.id,'slug',org.slug,'nameAr',org.name_ar,'nameEn',org.name_en,'description',org.description,'websiteUrl',org.website_url) end,'awardCategory',case when ac.id is null then null else jsonb_build_object('id',ac.id,'slug',ac.slug,'nameAr',ac.name_ar,'nameEn',ac.name_en,'description',ac.description) end,'ceremony',case when ceremony.id is null then null else jsonb_build_object('id',ceremony.id,'year',ceremony.year,'edition',ceremony.edition,'label',ceremony.label,'heldOn',ceremony.held_on,'sourceUrl',ceremony.source_url) end) order by r.position,r.id) from award_recognitions r left join award_organizations org on org.id=r.organization_id left join award_categories ac on ac.id=r.category_id left join award_ceremonies ceremony on ceremony.id=r.ceremony_id where r.title_id=t.id),'[]'::jsonb),
'contentWarnings',t.content_warnings,'analysisNotes',t.analysis_notes,
'sexualityRisk',t.sexuality_risk,'behavioralRisk',t.behavioral_risk,'theologyRisk',t.theology_risk,
'externalIds',jsonb_build_object('tmdbId',t.tmdb_id,'imdbId',t.imdb_id,'anilistId',t.anilist_id,'malId',t.mal_id),
'aliases',coalesce((select jsonb_agg(jsonb_build_object('id',a.id,'title',a.title,'language',a.language,'script',a.script,'isPreferred',a.is_preferred) order by a.is_preferred desc,a.title) from title_aliases a where a.title_id=t.id),'[]'::jsonb),
'trivia',coalesce((select jsonb_agg(v.text order by v.position) from title_trivia v where v.title_id=t.id),'[]'::jsonb),
'genres',coalesce((select jsonb_agg(jsonb_build_object('id',g.id,'slug',g.slug,'labelEn',g.label_en,'labelAr',g.label_ar,'descriptionEn',g.description_en,'descriptionAr',g.description_ar) order by g.position,g.slug) from title_genres tg join genres g on g.id=tg.value_id where tg.title_id=t.id),'[]'::jsonb),
'contributions',coalesce((select jsonb_agg(jsonb_build_object('id',e.id,'name',e.name,'kind',e.kind,'description',e.description,'aliases',coalesce((select jsonb_agg(jsonb_build_object('alias',ea.alias,'language',ea.language) order by ea.alias,ea.id) from entity_aliases ea where ea.entity_id=e.id),'[]'::jsonb),'artwork',coalesce((select jsonb_agg(jsonb_build_object('id',a.id,'url','/api/v1/artwork/'||a.id,'mimeType',a.mime_type,'width',a.width,'height',a.height,'byteSize',a.byte_size,'sha256',a.sha256,'originalFilename',a.original_filename,'focalX',a.focal_x,'focalY',a.focal_y,'role',m.role,'isPrimary',m.is_primary) order by m.is_primary desc,m.id) from media_asset_assignments m join media_assets a on a.id=m.asset_id where m.entity_id=e.id),'[]'::jsonb),'isPrimary',c.is_primary,'position',c.position,'roleId',r.id,'roleDescriptionEn',r.description_en,'roleDescriptionAr',r.description_ar,'role',r.slug,'roleLabelEn',r.label_en,'roleLabelAr',r.label_ar) order by c.position,e.sort_name) from contributions c join entities e on e.id=c.entity_id join roles r on r.id=c.role_id where c.title_id=t.id),'[]'::jsonb),
'relations',coalesce((select jsonb_agg(jsonb_build_object('id',r.id,'workId',other.id,'canonicalTitle',other.canonical_title,'titleAr',other.title_ar,'kind',r.kind,'direction',case when r.source_title_id=t.id then 'outgoing' else 'incoming' end,'notes',r.notes) order by other.sort_title,r.id) from title_relations r join titles other on other.id=case when r.source_title_id=t.id then r.target_title_id else r.source_title_id end where r.source_title_id=t.id or r.target_title_id=t.id),'[]'::jsonb),
'artwork',coalesce((select jsonb_agg(jsonb_build_object('id',a.id,'url','/api/v1/artwork/'||a.id,'mimeType',a.mime_type,'width',a.width,'height',a.height,'byteSize',a.byte_size,'sha256',a.sha256,'originalFilename',a.original_filename,'focalX',a.focal_x,'focalY',a.focal_y,'role',m.role,'isPrimary',m.is_primary) order by m.is_primary desc,m.id) from media_asset_assignments m join media_assets a on a.id=m.asset_id where m.title_id=t.id),'[]'::jsonb),
'installments',coalesce((select jsonb_agg(jsonb_build_object(
  'id',i.id,'kind',i.kind,'position',i.position,'title',i.title,'summary',i.summary,'releaseDate',i.release_date,'runtimeMinutes',i.runtime_minutes,'status',i.status,
  'classification',jsonb_build_object('audience',coalesce(i.audience_override,t.audience),'age',coalesce(i.age_override,t.age),'sexualityRisk',coalesce(i.sexuality_risk_override,t.sexuality_risk),'behavioralRisk',coalesce(i.behavioral_risk_override,t.behavioral_risk),'theologyRisk',coalesce(i.theology_risk_override,t.theology_risk)),'classificationOverrides',jsonb_build_object('audience',i.audience_override,'age',i.age_override,'sexualityRisk',i.sexuality_risk_override,'behavioralRisk',i.behavioral_risk_override,'theologyRisk',i.theology_risk_override),'releaseState',case when i.release_date is null then 'unknown' when i.release_date>current_date then 'upcoming' else 'released' end,'externalReferences',coalesce((select jsonb_agg(jsonb_build_object('id',x.id,'provider',x.provider,'externalId',x.external_id,'url',x.url) order by x.provider,x.id) from external_identities x where x.installment_id=i.id),'[]'::jsonb),'mediaFiles',coalesce((select jsonb_agg(jsonb_build_object('id',f.id,'durationSeconds',f.duration_seconds,'jellyfinLinked',exists(select 1 from jellyfin_items j where j.media_file_id=f.id),'tracks',coalesce((select jsonb_agg(jsonb_build_object('id',mt.id,'kind',mt.kind,'streamIndex',mt.stream_index,'language',mt.language,'codec',mt.codec,'title',mt.title,'isDefault',mt.is_default,'isForced',mt.is_forced) order by mt.stream_index,mt.id) from media_tracks mt where mt.media_file_id=f.id),'[]'::jsonb)) order by f.id) from media_files f where f.installment_id=i.id),'[]'::jsonb),'createdAt',i.created_at,'updatedAt',i.updated_at,
  'externalIds',jsonb_build_object('tmdbId',i.tmdb_id,'imdbId',i.imdb_id,'anilistId',i.anilist_id,'malId',i.mal_id),
  'scores',(select jsonb_build_object('updatedAt',s.updated_at,'story',s.story,'characters',s.characters,'depth',s.depth,'worldBuilding',s.world_building,'originality',s.originality,'craft',s.craft) from installment_scores s where s.installment_id=i.id),
  'hasMediaFile',exists(select 1 from media_files f where f.installment_id=i.id),
  'artwork',coalesce((select jsonb_agg(jsonb_build_object('id',a.id,'url','/api/v1/artwork/'||a.id,'mimeType',a.mime_type,'width',a.width,'height',a.height,'byteSize',a.byte_size,'sha256',a.sha256,'originalFilename',a.original_filename,'focalX',a.focal_x,'focalY',a.focal_y,'role',m.role,'isPrimary',m.is_primary) order by m.is_primary desc,m.id) from media_asset_assignments m join media_assets a on a.id=m.asset_id where m.installment_id=i.id),'[]'::jsonb),
  'episodes',coalesce((select jsonb_agg(jsonb_build_object('id',e.id,'classification',jsonb_build_object('audience',coalesce(i.audience_override,t.audience),'age',coalesce(i.age_override,t.age),'sexualityRisk',coalesce(i.sexuality_risk_override,t.sexuality_risk),'behavioralRisk',coalesce(i.behavioral_risk_override,t.behavioral_risk),'theologyRisk',coalesce(i.theology_risk_override,t.theology_risk)),'artwork',coalesce((select jsonb_agg(jsonb_build_object('id',a.id,'url','/api/v1/artwork/'||a.id,'mimeType',a.mime_type,'width',a.width,'height',a.height,'byteSize',a.byte_size,'sha256',a.sha256,'originalFilename',a.original_filename,'focalX',a.focal_x,'focalY',a.focal_y,'role',m.role,'isPrimary',m.is_primary) order by m.is_primary desc,m.id) from media_asset_assignments m join media_assets a on a.id=m.asset_id where m.episode_id=e.id),'[]'::jsonb),'mediaFiles',coalesce((select jsonb_agg(jsonb_build_object('id',f.id,'durationSeconds',f.duration_seconds,'jellyfinLinked',exists(select 1 from jellyfin_items j where j.media_file_id=f.id),'tracks',coalesce((select jsonb_agg(jsonb_build_object('id',mt.id,'kind',mt.kind,'streamIndex',mt.stream_index,'language',mt.language,'codec',mt.codec,'title',mt.title,'isDefault',mt.is_default,'isForced',mt.is_forced) order by mt.stream_index,mt.id) from media_tracks mt where mt.media_file_id=f.id),'[]'::jsonb)) order by f.id) from media_files f where f.episode_id=e.id),'[]'::jsonb),'createdAt',e.created_at,'updatedAt',e.updated_at,'number',e.number::text,'position',e.position,'title',e.title,'summary',e.summary,'releaseDate',e.release_date,'runtimeMinutes',e.runtime_minutes,'releaseState',case when e.release_date is null then 'unknown' when e.release_date>current_date then 'upcoming' else 'released' end,'hasMediaFile',exists(select 1 from media_files f where f.episode_id=e.id)) order by e.position,e.id) from episodes e where e.installment_id=i.id),'[]'::jsonb)
) order by i.position,i.id) from installments i where i.title_id=t.id),'[]'::jsonb))"#;

// Dashboard weighted-average-v1: IEEE double arithmetic and ordered aggregation match
// the shared JavaScript model, including its positive Math.round ties. Numeric decimal
// arithmetic changes borderline values. Only complete criteria contribute.
pub(super) const SCORE_VALUE: &str = r#"case when
s.story between 0 and 10 and s.characters between 0 and 10 and s.depth between 0 and 10
and s.world_building between 0 and 10 and s.originality between 0 and 10 and s.craft between 0 and 10
then s.story::double precision*0.25+s.characters::double precision*0.20+s.depth::double precision*0.20+s.world_building::double precision*0.10+s.originality::double precision*0.10+s.craft::double precision*0.15 end"#;

pub(super) fn summary() -> String {
    format!(
        "{SUMMARY} || jsonb_build_object('score',(select jsonb_build_object('rating',floor(avg(rating order by position,id)*10+0.5)/10,'scored',count(rating),'total',count(*)) from (select {SCORE_VALUE} rating,i.position,i.id from installments i left join installment_scores s on s.installment_id=i.id where i.title_id=t.id) rated))"
    )
}
