import { avatarAssetFiles } from "virtual:arcadia-avatar-catalog";

export type AvatarAsset = {
  key: string;
  label: string;
};

function labelForAvatarAsset(key: string) {
  return key
    .replace(/\.[a-z0-9]+$/i, "")
    .replaceAll("/", " · ")
    .replaceAll("-", " ");
}

/** Every safe image under `public/media/avatars`, regenerated by Vite whenever the app builds. */
export const avatarAssets: readonly AvatarAsset[] = avatarAssetFiles.map((key) => ({
  key,
  label: labelForAvatarAsset(key),
}));
