/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as EntitiesRouteImport } from './routes/entities'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ApiAgentRouteImport } from './routes/api.agent'
import { Route as EntitiesIndexRouteImport } from './routes/entities.index'
import { Route as EntitiesEntityIdRouteImport } from './routes/entities.$entityId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesRoute = EntitiesRouteImport.update({
  id: '/entities',
  path: '/entities',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentRoute = ApiAgentRouteImport.update({
  id: '/api/agent',
  path: '/api/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesIndexRoute = EntitiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EntitiesRoute,
} as any)
const EntitiesEntityIdRoute = EntitiesEntityIdRouteImport.update({
  id: '/$entityId',
  path: '/$entityId',
  getParentRoute: () => EntitiesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/entities': typeof EntitiesRouteWithChildren
  '/feed': typeof FeedRoute
  '/library': typeof LibraryRoute
  '/api/agent': typeof ApiAgentRoute
  '/entities/$entityId': typeof EntitiesEntityIdRoute
  '/entities/': typeof EntitiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/feed': typeof FeedRoute
  '/library': typeof LibraryRoute
  '/api/agent': typeof ApiAgentRoute
  '/entities/$entityId': typeof EntitiesEntityIdRoute
  '/entities': typeof EntitiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/entities': typeof EntitiesRouteWithChildren
  '/feed': typeof FeedRoute
  '/library': typeof LibraryRoute
  '/api/agent': typeof ApiAgentRoute
  '/entities/$entityId': typeof EntitiesEntityIdRoute
  '/entities/': typeof EntitiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/entities'
    | '/feed'
    | '/library'
    | '/api/agent'
    | '/entities/$entityId'
    | '/entities/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/feed'
    | '/library'
    | '/api/agent'
    | '/entities/$entityId'
    | '/entities'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/entities'
    | '/feed'
    | '/library'
    | '/api/agent'
    | '/entities/$entityId'
    | '/entities/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  EntitiesRoute: typeof EntitiesRouteWithChildren
  FeedRoute: typeof FeedRoute
  LibraryRoute: typeof LibraryRoute
  ApiAgentRoute: typeof ApiAgentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities': {
      id: '/entities'
      path: '/entities'
      fullPath: '/entities'
      preLoaderRoute: typeof EntitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent': {
      id: '/api/agent'
      path: '/api/agent'
      fullPath: '/api/agent'
      preLoaderRoute: typeof ApiAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities/': {
      id: '/entities/'
      path: '/'
      fullPath: '/entities/'
      preLoaderRoute: typeof EntitiesIndexRouteImport
      parentRoute: typeof EntitiesRoute
    }
    '/entities/$entityId': {
      id: '/entities/$entityId'
      path: '/$entityId'
      fullPath: '/entities/$entityId'
      preLoaderRoute: typeof EntitiesEntityIdRouteImport
      parentRoute: typeof EntitiesRoute
    }
  }
}

interface EntitiesRouteChildren {
  EntitiesEntityIdRoute: typeof EntitiesEntityIdRoute
  EntitiesIndexRoute: typeof EntitiesIndexRoute
}

const EntitiesRouteChildren: EntitiesRouteChildren = {
  EntitiesEntityIdRoute: EntitiesEntityIdRoute,
  EntitiesIndexRoute: EntitiesIndexRoute,
}

const EntitiesRouteWithChildren = EntitiesRoute._addFileChildren(
  EntitiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  EntitiesRoute: EntitiesRouteWithChildren,
  FeedRoute: FeedRoute,
  LibraryRoute: LibraryRoute,
  ApiAgentRoute: ApiAgentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
