import {
  AwardIcon,
  BookOpenIcon,
  Building2Icon,
  ClapperboardIcon,
  FilmIcon,
  GitBranchIcon,
  GlobeIcon,
  ListVideoIcon,
  NotebookTextIcon,
  TagsIcon,
  UsersIcon,
  WandSparklesIcon,
} from "lucide-react";

export const collections = [
  {
    slug: "works",
    title: "الأعمال",
    description: "العناوين، التصنيف العائلي، التقييمات، وكل ما تعرفونه عن العمل.",
    icon: FilmIcon,
    columns: ["العمل", "النوع", "السنة", "حالة التحرير", "التقييم", "آخر تعديل"],
    action: "عمل جديد",
  },
  {
    slug: "installments",
    title: "المواسم والأفلام",
    description: "بنية العمل، الأجزاء، الترتيب، ومواعيد الإصدار.",
    icon: ClapperboardIcon,
    columns: ["العمل", "الجزء", "النوع", "الترتيب", "الإصدار"],
    action: "جزء جديد",
  },
  {
    slug: "episodes",
    title: "الحلقات",
    description: "العناوين، الأرقام، الصور، المدة، والهويات الخارجية لكل حلقة.",
    icon: ListVideoIcon,
    columns: ["العمل والموسم", "الحلقة", "العنوان", "المدة", "الإصدار"],
    action: "حلقة جديدة",
  },
  {
    slug: "people",
    title: "الأشخاص",
    description: "الأسماء والبدائل والمساهمات والصور والمراجع الخارجية.",
    icon: UsersIcon,
    columns: ["الشخص", "الاسم البديل", "المساهمات", "الصورة", "آخر تعديل"],
    action: "شخص جديد",
  },
  {
    slug: "studios",
    title: "الاستوديوهات",
    description: "الاستوديوهات والمؤسسات والأعمال التي شاركت فيها.",
    icon: Building2Icon,
    columns: ["الاستوديو", "البلد", "المساهمات", "العلاقات", "آخر تعديل"],
    action: "استوديو جديد",
  },
  {
    slug: "planets",
    title: "العوالم",
    description: "الأكوان والسلاسل التي تجمع أعمالاً مرتبطة.",
    icon: GlobeIcon,
    columns: ["العالم", "المعرّف", "الأعمال", "الوصف"],
    action: "عالم جديد",
  },
  {
    slug: "relationships",
    title: "العلاقات",
    description: "التتابع، الاقتباس، الأعمال الجانبية، وعلاقات المؤسسات.",
    icon: GitBranchIcon,
    columns: ["المصدر", "نوع العلاقة", "الهدف", "ملاحظات"],
    action: "علاقة جديدة",
  },
  {
    slug: "scores",
    title: "التقييمات والتحليل",
    description: "المعايير الستة، النتائج التحريرية، وملاحظات تحليل الأعمال.",
    icon: WandSparklesIcon,
    columns: ["العمل", "الجزء", "القصة", "الشخصيات", "العمق", "المجموع"],
    action: "تقييم جديد",
  },
  {
    slug: "awards",
    title: "الجوائز",
    description: "المنظمات والفئات والحفلات والترشيحات والنتائج.",
    icon: AwardIcon,
    columns: ["المنظمة", "الحفل", "الفئة", "العمل", "النتيجة"],
    action: "جائزة جديدة",
  },
  {
    slug: "vocabularies",
    title: "المفردات والترجمات",
    description: "الأنواع والنبرات والوسوم والبلدان والأدوار وتسمياتها.",
    icon: TagsIcon,
    columns: ["المفردة", "الفئة", "العربية", "الإنجليزية", "الاستخدام"],
    action: "مفردة جديدة",
  },
  {
    slug: "credits",
    title: "المساهمات",
    description: "ربط الأشخاص والمؤسسات بالأعمال والأدوار الصحيحة.",
    icon: BookOpenIcon,
    columns: ["العمل", "الكيان", "الدور", "المساهمة الرئيسية"],
    action: "مساهمة جديدة",
  },
  {
    slug: "evidence",
    title: "المراجع والملاحظات",
    description: "مصادر المعلومات، التحقق منها، والملاحظات التحريرية.",
    icon: NotebookTextIcon,
    columns: ["السجل", "الحقل", "المصدر", "حالة التحقق", "آخر مراجعة"],
    action: "مرجع جديد",
  },
] as const;

export function collectionFor(slug: string) {
  return collections.find((collection) => collection.slug === slug);
}
